from admin.workers_settings.remove_worker import remove_worker_handler
from admin.workers_settings.show_worker import show_worker_handler
from admin.workers_settings.worker_balance import worker_balance_handler
from admin.workers_settings.add_worker import add_worker_cp_handler
from admin.workers_settings.common import worker_settings_handler
