from admin.order_settings.order_settings import order_settings_handler
from admin.order_settings.edit_amount import edit_order_amount_handler
from admin.order_settings.request_photos import request_photos_handler
from admin.order_settings.return_to_worker import return_order_to_worker_handler
from admin.order_settings.unset_working_on_it import unset_working_on_it_handler
from admin.order_settings.contact_user import contact_user_handler
from admin.order_settings.delete_order import delete_order_handler